# Generated by Django 3.0.14 on 2024-11-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('codprod', models.AutoField(primary_key=True, serialize=False)),
                ('nameprod', models.CharField(max_length=100)),
                ('categoryprod', models.CharField(max_length=500)),
                ('descprod', models.TextField()),
                ('brandprod', models.CharField(max_length=50)),
                ('manudateprod', models.DateField()),
                ('weightprod', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PriceProd',
            fields=[
                ('codprice', models.AutoField(primary_key=True, serialize=False)),
                ('priceprod', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dateverify', models.DateField()),
                ('codprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo', to='product.Product')),
            ],
        ),
    ]
