# Generated by Django 3.0.14 on 2024-12-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoryprod',
            field=models.CharField(max_length=100),
        ),
    ]
