# Generated by Django 3.0.14 on 2024-10-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcli', models.CharField(max_length=7, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200)),
                ('senha', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('entrega', models.CharField(max_length=250)),
                ('codcli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteloja.Clientes')),
            ],
        ),
    ]
